[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
derive_more = "0.99.17"
ndarray = "0.15.6"
num = "0.4.1"
regex = "1.10.2"
